title: Thiago Nunes # your name (or website title) here
logo: "/images/avatar_site.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10 anos de experiência ajudando clientes a melhorarem suas rotinas através de software, com foco na entrega de valor ao negócio através de dados. 
  Graduado em Ciência da Computação pela Federal do Maranhão e Mestre Universidade Estadual do Maranhão. 

  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-76434204-1 # your Google Analytics tracking ID here
