title: Thiago Nunes # your name (or website title) here
logo: "/images/avatar_site.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10 anos de experiência ajudando clientes a melhorarem suas rotinas através de software, com foco na entrega de valor ao negócio através de dados. 
  Graduado em Ciência da Computação pela Federal do Maranhão e Mestre pela Universidade Estadual do Maranhão. 

  <br><br>

  <a href="https://www.linkedin.com/in/thiagotns/">
    <img src="/images/linkedin.png?raw=true" style="width: 30px"/>
  </a>

  <a href="https://www.instagram.com/thiagotns/">
    <img src="/images/instagram.png?raw=true" style="width: 30px; margin-left: 4px"/>
  </a>

  <a href="https://twitter.com/thiago_tns">
    <img src="/images/twitter.png?raw=true" style="width: 30px; margin-left: 4px"/>
  </a>

  <a href="{{ site.github.owner_url }}">
    <img src="/images/github.png?raw=true" style="width: 30px; margin-left: 4px"/>
  </a>

theme: jekyll-theme-minimal
google_analytics: UA-76434204-1 # your Google Analytics tracking ID here
