title: Thiago Nunes # your name (or website title) here
logo: "/images/avatar_site.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10 anos de experiência ajudando clientes a melhorarem suas rotinas através de software. O foco do meu trabalho é entregar valor ao negócio através dos dados. 
  <br><br>
  Tenho graduação em Ciência da Computação pela Universidade Federal do Maranhão e Mestrado Profissional em Engenharia da Computação e Sistema pela Universidade Estadual do Maranhão. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
